name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  pull_request_comment:
    name: PR comment
    if: ${{ !contains(github.event.head_commit.message, '/pull/') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PPPPPPPPUUUUUUULLLLLLLLL
    else: ${{ !contains(github.event.head_commit.message, '/pull/')}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
