name: "Testing"

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  test_the_action:
    if: "!contains(github.event.head_commit.message, 'build')"
    name: Test the action
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: suisei-cn/actions-download-file@master
        id: downloadfile
        name: Download a file
        with:
          url: "[API Endpoint](https://api.github.com/repos/suisei-cn/actions-download-file)"
          target: public/
          auto-match: true
  test_the_action1:
    if: "!contains(github.event.head_commit.message, 'deploy')"
    name: Test the action
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: suisei-cn/actions-download-file@master
        id: downloadfile
        name: Download a file
        with:
          url: "[API Endpoint](https://api.github.com/repos/suisei-cn/actions-download-file)"
          target: public/
          auto-match: true

      - name: Display the file
        run: head -n8 public/actions-download-file
