name: "Testing"

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build_action:
    if: "!contains(github.event.head_commit.message, 'build')"
    name: Build Action
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: python test1.py
        shell: sh

  deploy_action:
    if: "!contains(github.event.head_commit.message, 'deploy')"
    name: Deploy Action
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: suisei-cn/actions-download-file@master
        id: downloadfile
        name: Deploy Action
        with:
          url: "[API Endpoint](https://api.github.com/repos/suisei-cn/actions-download-file)"
          target: public/
          auto-match: true

      - name: Display the file
        run: head -n8 public/actions-download-file
